<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>HdcSharp</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <Version>0.1.0</Version>
    <PackageId>HdcSharp</PackageId>
    <Description>纯 C# 实现的 OpenHarmony HDC 宿主侧协议库（WiFi/TCP）。</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Pipelines" Version="8.0.0" />
  </ItemGroup>
</Project>
